---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: nevermind
  resolve_with_librarian_puppet: true
  require_chef_for_busser: true

platforms:
  - name: centos-64-x64-vbox4210
    driver_plugin: vagrant
    driver_config:
      box: centos-64-x64-vbox4210
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box
  - name: ubuntu-server-12042-x64-vbox4210
    driver_plugin: vagrant
    driver_config:
      box: ubuntu-server-12042-x64-vbox4210
      box_url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box

suites:
  - name: go-server
  - name: go-agent
